# -*- coding: utf-8 -*-
"""Task 2 of 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKZo8fCiaWRxy_1FlCxgAFr0U7O9-i_S
"""



"""# Integrating Google Custom Search JSON API

This notebook demonstrates how to perform web searches and display results using the Google Custom Search JSON API.

**Note:** Using the Google Custom Search JSON API requires a valid API key and Search Engine ID. Please ensure you have obtained this information.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install google-api-python-client

"""## Set up API Key and Search Engine ID

Please fill in your Google API Key and Search Engine ID in the variables below.
"""

from googleapiclient.discovery import build

# You can change the Google API key and search engine ID to your own ones #
GOOGLE_API_KEY = "AIzaSyA0SQzDbPulj-gwhvSq2zw70uHnzg5drqo"
GOOGLE_CSE_ID = "f79a03541e7af4ac1"

"""## Write Search Function

This function uses the Google Custom Search JSON API to perform a search.
"""

def search_web(query):
    """
    Performs a web search using the Google Custom Search JSON API.

    Args:
        query: The search query string.

    Returns:
        The JSON response from the API, or None if an error occurred.
    """
    try:
        # Build a service object for the Custom Search API
        service = build("customsearch", "v1", developerKey=GOOGLE_API_KEY)

        # Execute the search
        res = service.cse().list(q=query, cx=GOOGLE_CSE_ID).execute()

        return res
    except Exception as e:
        print(f"Error during Google Custom Search API call: {e}")
        return None

"""## Process and Display Results

This function parses the JSON response returned from the Google Custom Search API and extracts relevant information.
"""

def parse_results(json_response):
    """
    Parses the JSON response from the Google Custom Search API and extracts relevant information.

    Args:
        json_response: The JSON response from the Google Custom Search API.

    Returns:
        A list of dictionaries, where each dictionary represents a search result
        with 'title', 'url', and 'snippet' keys, or an empty list if no results
        could be parsed or found.
    """
    search_results = []

    # Check if the JSON response is valid and contains the 'items' key
    if json_response and 'items' in json_response:
        for item in json_response['items']:
            # Extract title, link (url), and snippet
            title = item.get('title')
            url = item.get('link')
            snippet = item.get('snippet')

            # Append the extracted information to the results list
            if title and url: # Ensure at least title and URL are present
                search_results.append({
                    'title': title,
                    'url': url,
                    'snippet': snippet if snippet else 'No snippet available.'
                })

    return search_results

"""## Execute Search

This block will prompt you to enter a search query, then perform the search and display the results.
"""

# Main execution block
if __name__ == "__main__":
    # Get search query from user input
    search_query = input("Please enter your search query: ")

    if search_query:
        print(f"Searching for: {search_query}")

        # Call search_web to get the JSON response
        search_results_json = search_web(search_query)

        if search_results_json:
            print("Successfully retrieved search results from Google API. Attempting to parse results...")
            # Call parse_results to get the parsed data
            parsed_data = parse_results(search_results_json)

            if parsed_data:
                print(f"\nSearch results for '{search_query}':")
                for i, result in enumerate(parsed_data):
                    print(f"\nResult {i + 1}:")
                    print(f"  Title: {result['title']}")
                    print(f"  URL: {result['url']}")
                    print(f"  Snippet: {result['snippet']}")
            else:
                print("No search results could be parsed from the JSON response.")
        else:
            print("Failed to retrieve search results from Google API.")
    else:
        print("Search query cannot be empty.")