# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CBD8fOCBkJJ4p0CBb2KFAmXTSgrllVG
"""

# Import the Python SDK
import google.generativeai as genai
# Used to securely store your API key
from google.colab import userdata

GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

# Initialize the Gemini API
gemini_model = genai.GenerativeModel('models/gemini-2.5-flash')

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

user_question = input("Please enter your question:")
response = gemini_model.generate_content(user_question)
print("LLM's answer：")
print(response.text)

